# Kubernetes deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visual-query-builder
  labels:
    app: visual-query-builder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visual-query-builder
  template:
    metadata:
      labels:
        app: visual-query-builder
    spec:
      containers:
      - name: app
        image: visual-query-builder:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: pg-host
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: pg-port
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: pg-database
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: pg-user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: pg-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/schema/tables
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/schema/tables
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: visual-query-builder-service
spec:
  selector:
    app: visual-query-builder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  database-url: "postgresql://username:password@host:5432/database"
  pg-host: "localhost"
  pg-port: "5432"
  pg-database: "querybuilder"
  pg-user: "postgres"
  pg-password: "your-password"